# Yuxi Initialization Script for PowerShell
# 基于 .env.template 蓝本生成 .env；询问缺失的必填项，自动生成缺失的密钥。
# Note: API keys will be visible during input - use with care

###############################################################################
# 通用 helper
###############################################################################

# 生成指定字节数的随机十六进制串（Windows PowerShell 5.1 基于 .NET Framework，
# 不支持静态 Fill 方法，必须用 Create().GetBytes() 实例方法）
function New-RandomHex($ByteCount) {
    $bytes = [byte[]]::new($ByteCount)
    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    try {
        $rng.GetBytes($bytes)
    } finally {
        $rng.Dispose()
    }
    return -join ($bytes | ForEach-Object { $_.ToString("x2") })
}

# 检查 .env 中某变量是否已有真值（等号后第一个字符非空白、非 #）
function Test-EnvValue($Name) {
    $pattern = '^' + [regex]::Escape($Name) + '=[^\s#]'
    return [bool](Select-String -Path ".env" -Pattern $pattern -Quiet)
}

# 读取 .env 中某变量的当前值（不含键名），不存在则返回空串
function Get-EnvValue($Name) {
    $match = Select-String -Path ".env" -Pattern "^$Name=(.*)$" -Quiet:$false | Select-Object -First 1
    if ($null -eq $match) {
        return ""
    }
    $line = $match.Line
    $idx = $line.IndexOf('=')
    if ($idx -lt 0) {
        return ""
    }
    return $line.Substring($idx + 1)
}

# 幂等写入 .env：
#   - 已存在且有真值（等号后第一个字符非空白/非 #） → 跳过（保护用户已有配置）
#   - 存在但为模板占位（KEY=  # 注释）                 → 原地替换该行
#   - 完全不存在                                         → 追加到末尾
# 逐行处理避免 regex 多行模式在 PS 5.1 上的解析陷阱
function Update-EnvVar($Name, $Value) {
    $envPath = (Resolve-Path ".env").Path
    $lines = [System.IO.File]::ReadAllLines($envPath)
    $matchedLine = -1
    for ($i = 0; $i -lt $lines.Count; $i++) {
        if ($lines[$i] -notmatch ('^' + [regex]::Escape($Name) + '=')) {
            continue
        }
        # 提取等号后的内容
        $idx = $lines[$i].IndexOf('=')
        $val = $lines[$i].Substring($idx + 1)
        if ($val -match '^\s*(#|$)') {
            # 空值或仅注释 → 替换该行
            $matchedLine = $i
        } else {
            # 已有真值 → 跳过整个写入
            return
        }
    }
    if ($matchedLine -ge 0) {
        $lines[$matchedLine] = "$Name=$Value"
        $content = ($lines -join "`n") + "`n"
        [System.IO.File]::WriteAllText($envPath, $content, [System.Text.UTF8Encoding]::new($false))
    } else {
        Add-Content -Path ".env" -Value "`n$Name=$Value" -Encoding UTF8
    }
}

# 删除 .env 中所有 KEY=  后跟空白/可选注释的行（即模板占位但用户未填的行）
# 保留所有 KEY=真值 行（包括基础设施默认值和用户实际填的值）
function Remove-EmptyPlaceholders {
    $envPath = (Resolve-Path ".env").Path
    $lines = [System.IO.File]::ReadAllLines($envPath)
    $kept = @()
    $autoGenerated = @("JWT_SECRET_KEY", "YUXI_INSTANCE_ID")
    foreach ($line in $lines) {
        $idx = $line.IndexOf('=')
        if ($idx -gt 0) {
            $name = $line.Substring(0, $idx)
            if ($autoGenerated -contains $name) {
                # 自动生成项必须留在模板原位置，后续 Update-EnvVar 才能原地写入真实值。
                $kept += $line
                continue
            }
        }
        # 匹配：KEY=  后跟空白（0+）再可选注释的行
        if ($line -match '^[A-Z_][A-Z0-9_]*=\s*(#.*)?$') {
            continue
        }
        $kept += $line
    }
    $content = ($kept -join "`n") + "`n"
    [System.IO.File]::WriteAllText($envPath, $content, [System.Text.UTF8Encoding]::new($false))
}

# 询问用户输入并写回 .env：
#   - 已有非空值 → 跳过
#   - 必填（required）：非交互式写入明显占位符 + 警告（不退出）；交互式空输入循环要求重新输入
#   - 可选（optional）：非交互式静默跳过；交互式空输入也跳过
function Read-UserInput($Name, $Prompt, [string]$Required = "required") {
    if (Test-EnvValue $Name) {
        return
    }
    # 非交互式环境（管道 / 重定向）处理：required 写占位符 + 警告，optional 静默跳过
    if ([Console]::IsInputRedirected) {
        if ($Required -eq "required") {
            Write-Host "⚠️  非交互式环境无法询问 $Name，已写入占位符 __REPLACE_ME__$Name__；请事后手动编辑 .env 替换为真实值" -ForegroundColor Yellow
            Update-EnvVar $Name "__REPLACE_ME__$Name__"
        }
        return
    }
    $input = ""
    if ($Required -eq "required") {
        while ([string]::IsNullOrEmpty($input)) {
            $input = Read-Host $Prompt
            if ([string]::IsNullOrEmpty($input)) {
                Write-Host "❌ 不能为空，请重新输入" -ForegroundColor Red
            }
        }
    } else {
        $input = Read-Host "$Prompt (直接回车跳过)"
    }
    if (-not [string]::IsNullOrEmpty($input)) {
        Update-EnvVar $Name $input
    }
}

###############################################################################
# 主流程
###############################################################################

Write-Host "🚀 Initializing Yuxi project..." -ForegroundColor Cyan
Write-Host "==================================" -ForegroundColor Cyan

# 第 1 步：确保 .env 存在（以 .env.template 为蓝本）
if (Test-Path ".env") {
    Write-Host "✅ .env 已存在，跳过复制" -ForegroundColor Green
} else {
    if (-not (Test-Path ".env.template")) {
        Write-Host "❌ .env.template 不存在，无法初始化" -ForegroundColor Red
        exit 1
    }
    Copy-Item ".env.template" ".env"
    Write-Host "✅ 基于 .env.template 创建 .env" -ForegroundColor Green
}

# 删除模板占位但用户未填的行（如 TAVILY_API_KEY= ），避免污染用户配置
Remove-EmptyPlaceholders

# 第 2 步：补齐缺失的密钥（脚本可生成项先生成，避免后续交互中断留下空值）
Update-EnvVar "JWT_SECRET_KEY" (New-RandomHex 32)
Update-EnvVar "YUXI_INSTANCE_ID" ("instance-" + (New-RandomHex 8))

# 第 3 步：补齐缺失项
Write-Host ""
Write-Host "🔑 SiliconFlow API Key（首次必填，用于调用大模型）" -ForegroundColor Yellow
Write-Host "Get your API key from: https://cloud.siliconflow.cn/i/Eo5yTHGJ" -ForegroundColor Blue
Read-UserInput "SILICONFLOW_API_KEY" "请输入 SILICONFLOW_API_KEY" "required"

Write-Host ""
Write-Host "🔍 Tavily API Key（可选，用于搜索服务）" -ForegroundColor Yellow
Write-Host "Get your API key from: https://app.tavily.com/" -ForegroundColor Blue
Read-UserInput "TAVILY_API_KEY" "请输入 TAVILY_API_KEY" "optional"

# 第 4 步：拉取 Docker 镜像
Write-Host ""
Write-Host "📦 Pulling Docker images..." -ForegroundColor Cyan
Write-Host "=========================" -ForegroundColor Cyan

$images = @(
    "python:3.12-slim",
    "node:24-slim",
    "milvusdb/milvus:v2.5.6",
    "neo4j:5.26",
    "minio/minio:RELEASE.2023-03-20T20-16-18Z",
    "ghcr.io/astral-sh/uv:0.7.2",
    "quay.io/coreos/etcd:v3.5.5",
    "postgres:16",
    "redis:7-alpine"
)

foreach ($image in $images) {
    Write-Host "🔄 Pulling ${image}..." -ForegroundColor Yellow
    try {
        & scripts/pull_image.ps1 $image
        if ($LASTEXITCODE -eq 0) {
            Write-Host "✅ Successfully pulled ${image}" -ForegroundColor Green
        } else {
            Write-Host "❌ Failed to pull ${image}" -ForegroundColor Red
            exit 1
        }
    } catch {
        Write-Host "❌ Error pulling ${image}: $_" -ForegroundColor Red
        exit 1
    }
}

$sandboxImage = "enterprise-public-cn-beijing.cr.volces.com/vefaas-public/all-in-one-sandbox:latest"
Write-Host "🔄 Pulling ${sandboxImage}..." -ForegroundColor Yellow
docker pull $sandboxImage
if ($LASTEXITCODE -eq 0) {
    Write-Host "✅ Successfully pulled ${sandboxImage}" -ForegroundColor Green
} else {
    Write-Host "❌ Failed to pull ${sandboxImage}" -ForegroundColor Red
    exit 1
}

Write-Host ""
Write-Host "🎉 Initialization complete!" -ForegroundColor Green
Write-Host "==========================" -ForegroundColor Green
Write-Host "You can now run: .\scripts\manage.ps1 dev deploy" -ForegroundColor Cyan
Write-Host "This will start all services in development mode with hot-reload enabled." -ForegroundColor Cyan
